### ISSUE TITLE
Binary release with 17.5's (東方剛欲異聞) support?

### ISSUE THREAD

**Issue by gabrielwoj** [nyfair/foo_thbgm#10]
Hello, will there be an update to the ".fb2k-component" file with support to 17.5? If not, how can I compile one?

Thank you. And I highly appreciate your work with this project, I listen to Touhou songs nearly everyday!

**Comment by nyfair** [comment]
Yes, the 'latest' tag in the release page always built from git trunk

**Comment by gabrielwoj** [comment]
Thank you, I had no idea that the ".fb2k-component" was updated, due to the release still being "on Dec 7, 2020".

Have a good day and thank you once again for your work.
