### ISSUE TITLE
".pak" (from 13.5, 14.5 and 15.5) are not possible to play since latest update

### ISSUE THREAD

**Issue by gabrielwoj** [nyfair/foo_thbgm#11]
I'm unable to load songs from 13.5 (東方心綺楼), 14.5 (東方深秘録) and 15.5 (東方憑依華) games. It seems that it's no longer possible to load ".pak" files that the most recent fighting-games use.
![image](https://user-images.githubusercontent.com/13741779/146571920-a5d2c267-e44b-4522-aa24-c7dd68e97855.png)
![image](https://user-images.githubusercontent.com/13741779/146571958-630aa673-bd60-49d2-b2dd-97314962b281.png)
![image](https://user-images.githubusercontent.com/13741779/146571990-285157ca-cb43-4ce5-a19e-c94462fd2e7d.png)

I haven't modified any of my thxml's prior to updating to the latest version of the extension, and these games' songs were loading just fine (I did change the filenames of the .paks and thxmls, and started using English names for the songs, but even then, they were working just fine before).

Thanks.

**Comment by gabrielwoj** [comment]
I did copy the exact values from /src/東方心綺楼.txml, 東方心綺楼b.txml, 東方深秘録.thxml, 東方憑依華.thxml and 東方憑依華b.thxml, renaming my .pak files, and they still did not open, with the same errors as above.

**Comment by gabrielwoj** [comment]
What a peculiar bug. If I open 14.5 or 15.5's songs right after I launch foobar2000, they play normally, but if I play any other song with a different file extension (that aren't .thxml files), they will stop opening. I have to restart foobar2000 to be able to play these songs again.

It seems that 13.5 songs doesn't open no matter what.

**Comment by nyfair** [comment]
I don't have these games now and will look into this next week.

gabrielwoj ***@***.***> 于 2021年12月19日周日 上午12:40写道：

**Comment by gabrielwoj** [comment]
It seems that opening 17.5's songs cause 14.5 and 15.5 songs to stop loading, doesn't seem to be an issue with opening other unrelated file extensions as I previously thought.

Sorry for sending a lot of replies, I'm sending them individually so you can receive notifications regarding the issue.

**Comment by nyfair** [comment]
Thank you, could you try the following build?
[foo_thbgm test.zip](https://github.com/nyfair/foo_thbgm/files/7742687/foo_thbgm.test.zip)

**Comment by gabrielwoj** [comment]
Hello, I downloaded the build you provided and the problem has been indeed fixed. I can load all the previously affected games with no issue (including 13.5). Even if I play a song from 17.5, I can still play 13.5, 14.5 and 15.5 songs without having to restart foobar2000.

I quickly played at least 1 song per game, to see if everything works, and, well, everything works, from TH6 to TH18. Thank you very much.
