### ISSUE TITLE
Progressbar overlaps the main window of foobar2k when inf-looping feature enabled

### ISSUE THREAD

**Issue by CarterLi** [nyfair/foo_thbgm#3]
Well done on the "ThBGM Loop Forever" feature, but it should not mess the main UI of foobar2000, which looks ... really bad.
Can we reset the progressbar when the music looping? If not possible, can we let it stop at the end?

**Comment by nyfair** [comment]
Which UI plugin are you using? 
I just checked with WSH panels progress bar and fb2k's default progress bar, both of them stop at the end.

**Comment by CarterLi** [comment]
Foobox 4. You may download it here:
http://pan.baidu.com/s/1kTIF6wn#path=%252Ffbx_latest_version

![default](https://cloud.githubusercontent.com/assets/6134068/7739525/d4976144-ff94-11e4-90ef-7dc18bfcec0d.PNG)

**Comment by nyfair** [comment]
That progress bar is controlled by JScript code, you should ask its author to fix this
FYI
http://www.fooblog2000.com/2007-02/how-to-make-a-progress-bar/
$ifgreater($get(progress),0, {draw something})

**Comment by CarterLi** [comment]
Althougth the url you gave me doesn't help, I managed to find out where the progress bar is painted myself.
```JScript
// skin\foobox\guiext.js: 28
this.Paint = function(gr){
	if(this.Enabled){
		var progress = this.Value/(this.MaxValue - this.MinValue);
		if (progress > 1) {
			progress -= progress | 0;
		}
		var pos = (progress*this.Width)|0;
		if(fixedWidth){
			gr.DrawImage(ImgBg,this.X,this.Y,this.Width,h,0,0,ImgBg.Width,h,0);
			gr.DrawImage(ImgOverlay,this.X,this.Y,pos,h,0,0,pos,h,0);
		}
		else{
			DrawThemedBox(gr,this.X,this.Y,this.Width,h,ImgBg,paddingLeft,0,paddingRight,0);
			DrawThemedBox(gr,this.X,this.Y,pos,h,ImgOverlay,paddingLeft,0,paddingRight,0);
		}
		gr.DrawImage(ImgKnob,Math.floor(this.X+pos-(ImgKnob.Width/2)),this.Y,ImgKnob.Width,ImgKnob.Height,0,0,ImgKnob.Width,ImgKnob.Height,0);
	}
}
```
Simply reset the position to 0 if it exceeds 1. The code is ugly but it works...

**Comment by nyfair** [comment]
lol, awesome
